name: show gcc version

on:
  workflow_dispatch:
jobs:
  to-build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Show
        run: |
          gcc --version
          sudo apt-get update
          sudo apt-get -y upgrade gcc
          gcc --version
